* Introduction
Quasar Int is an app extension that makes use of [[https://github.com/pyxo-dev/qint][Qint]] to facilitate the i18n of
Quasar apps.

* Installation
#+begin_src sh
quasar ext add @pyxo/int
#+end_src

The extension will add a directory =src/int/= that contains the configuration.
It adds also a boot file =src/boot/int.(ts|js)=, that needs to be registered
manually in =quasar.conf.js > boot=.

The extension will also scaffold an example implementation in =src-int/=.

** Prompts
You will be prompted if your app has typescript support, if you answer yes, *.ts
files will be added instead of *.js.

* Uninstall
#+begin_src sh
quasar ext remove @quasar/int
#+end_src

You might also wish to remove the added directories =src/int=, =src-int= and the
boot file =src/boot/int.(ts|js)=.

* Features
- SSR support.
- Supports different URL modes: prefix (example.com/en), subdomain
  (en.example.com), host (example.co.uk), search-param (example.com?l=en), none
  (example.com)
- Supports the use of a language tag cookie.
- Can make use of the user's client language preferences (e.g. browser
  settings).
- Support for =hreflang= link tags.
- Language tags, Qint uses the term "language tag" to denote a language or a
  locale, and recommends the use of [[https://www.w3.org/International/articles/language-tags][BCP 47]] language tags.

* Documentation
API docs: [[https://wint.pyxo.net/api][wint]] | [[https://vint.pyxo.net/api][vint]] | [[https://qint.pyxo.net/api][qint]]

* Source code
Repository: [[https://github.com/pyxo-dev/quasar-app-extension-int][github.com/pyxo-dev/quasar-app-extension-int]]
Qint repository: [[https://github.com/pyxo-dev/qint][github.com/pyxo-dev/qint]]

Contributions are welcome!

* See also
- [[https://github.com/pyxo-dev/wint][Wint]] Web apps int.
- [[https://github.com/pyxo-dev/vint][Vint]] Vue int.
- [[https://github.com/pyxo-dev/qint][Qint]] Quasar int.
